swagger: "2.0"
info:
  version: "2.1.0"
  title: "My Api"
paths:
  /foo/{bar}:
    parameters:
      - name: "bar"
        in: "path"
        description: "demonstration of path param"
        required: true
        type: "string"
    get:
      description: "gets the bar"
      operationId: "myapi.controller.foo_handler"
      responses:
        200:
          description: OK;
          schema:
            type: object
        404:
           description: there is no bar

  /baz:
    post:
      description: "demonstration of post body"
      operationId: "myapi.controller.baz_handler"
      parameters:
        - in: body
          name: bazpostbody
          description: Represents a POST body
          schema:
            $ref: '#/definitions/baz_post'
      responses:
        200:
            description: "OK..."


definitions:
  baz_post:
    type: object
    required:
      - query_string
    properties:
      query_string:
        type: string
        description: "the raw query;"
